env: "local"
storage_path: "storage/storage.go"
http_server:
  address: "localhost:8080"
  timeout: 4s #время на чтение запроса и такое же отправку ответа
  idle-timeout: 60s #время жизни соединения с клиентом

